### ISSUE TITLE
JRDA Google Sheets Update

### ISSUE THREAD

**Issue by NSOMischiefManager** [AdamSmasherDerby/Statsbook-Tool#20] opened 2024-03-06 00:30 UTC
![image](https://github.com/AdamSmasherDerby/Statsbook-Tool/assets/162389213/c259f5bf-dbb9-41ca-baa2-414aa97fa772)

I am getting an error message when I try to upload a JRDA Link.

**Comment by AdamSmasherDerby** [comment] 2024-03-06 16:00
Can you please share the link that isn't working to help with debugging?Sent from my Galaxy
-------- Original message --------From: NSOMischiefManager ***@***.***> Date: 3/5/24  4:30 PM  (GMT-08:00) To: AdamSmasherDerby/Statsbook-Tool ***@***.***> Cc: Subscribed ***@***.***> Subject: [AdamSmasherDerby/Statsbook-Tool] JRDA Google Sheets Update (Issue
  #20) 
image.png (view on web)
I am getting an error message when I try to upload a JRDA Link.

**Comment by NSOMischiefManager** [comment] 2024-03-06 21:54
Hi! Thank you for getting back to me. The link I used is below. I set the
link to Anyone with the Link can View, also tried anyone with the link can
edit. Both gave me the same error. I greatly appreciate your help, the fact
that you created this amazing program, and that you added in an ability to
have it check JRDA Google Sheets. Let me know what else you need.

~Mischief

https://docs.google.com/spreadsheets/d/1AkXzWw5CS7uXOZKvVtUXNZWr7ErZLet6_mL91lJ_UlI/edit?usp=sharing

**Comment by NSOMischiefManager** [comment] 2024-03-09 14:31
Also, I am getting the same error message when I try to upload a statsbook
from my computer. It is a file I downloaded from the CRG Scoreboard, but
isn't allowing me to run it through the checker. I have attached that file
as well.

**Comment by AdamSmasherDerby** [comment] 2024-03-09 16:33
OK, it appears that JRDA updated their statsbook, but if there was an announcement, I didn't see it.  I'll see if I can get the software updated soon.

**Comment by NSOMischiefManager** [comment] 2024-03-09 17:00
Thank you for checking in on it. I appreciate all you do for the Roller
Derby world! You make the life of NSOs everywhere so much easier.

**Comment by AdamSmasherDerby** [comment] 2024-03-09 18:34
Fixed in https://github.com/AdamSmasherDerby/Statsbook-Tool/commit/45156e69e08b5127f0b04f0361a5d8391b9f3592 . 

So the issue is that I hard-coded all of the version numbers, and when the JRDA statsbook updated to 2024, even though literally nothing of significance had changed, the software lost its mind.  This has now hopefully been addressed.  If you feed it a 2025 statsbook (how?), it should now attempt to use the 2024 template, and throw a notification message.

Thanks for reporting the issue!

**Closed as completed by AdamSmasherDerby** 2024-03-09 18:34 UTC
